version: "3.5"

services:
  registry:
    image: registry
    ports:
      - "${REGISTRY_PORT}:5000"

  master:
    image: $REGISTRY_ADDR:$REGISTRY_PORT/$IMAGE_NAME
    volumes:
      - "nfsmountCC:/SRC"    # nfsmountCC is the volume created by docker-compose in the volumes section below.  /opt/ is the mount location inside of the container.
    user: root
    entrypoint: ["mpi_bootstrap", "role=master", "mpi_master_service_name=master", "mpi_worker_service_name=worker"]
    ports:
      - "${SSH_PORT}:22"
    networks:
      - net

  worker:
    image: $REGISTRY_ADDR:$REGISTRY_PORT/$IMAGE_NAME
    volumes:
      - "nfsmountCC:/SRC/"    # nfsmountCC is the volume created by docker-compose in the volumes section below.  /opt/ is the mount location inside of the container.
    user: root
    entrypoint: ["mpi_bootstrap", "role=worker", "mpi_master_service_name=master", "mpi_worker_service_name=worker"]
    networks:
      - net

networks:
  net:

volumes:
  nfsmountCC:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.193.200.114,nolock,soft,rw"       # IP of nfs server.  This is also where you put any options '-o' in standard option format
      device: ":/vol1/crisc"  # location on nfs server of file/dir you want to mount
